name: Deno CI

on: [push]

jobs:
  test:
    name: CI

    runs-on: ubuntu-latest

    steps:
     - name: Checkout repo
       uses: actions/checkout@v2

     - name: Setup Deno
       uses: denoland/setup-deno@v1
       with:
         deno-version: v1.x

     - name: Check format
       run: deno fmt --check

     # TODO: Currently `deno lint` is not working. The fix may take some time, so CI is disabled.
     #- name: Check lint
     #  run: deno lint

     - name: Run tests
       run: deno test --allow-run
